services:
  postgres:
    container_name: order-api-pg
    image: postgres:16.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: my_pass
      PG_DATA: /data/postgres
    volumes:
      - ./order-api-postgres-data:/data/postgres
      - ./init.sql:/docker-entrypoint-initdb.d/01-init.sql
    ports:
      - "5433:5432"
  redis:
    image: redis:7.2-alpine
    container_name: order-api-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - orderapi-network

volumes:
  redis_data:
    driver: local

networks:
  orderapi-network:
    driver: bridge
