services:
  postgres:
    container_name: order_api_postgres
    image: postgres:16.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: my_pass
      PG_DATA: /data/postgres
    volumes:
      - ./order-api-postgres-data:/data/postgres
    ports:
      - "5433:5432"
  redis:
    image: redis:7.2-alpine
    container_name: redis-orderapi
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - orderapi-network

volumes:
  redis_data:
    driver: local

networks:
  orderapi-network:
    driver: bridge
